### ISSUE TITLE
The query is not executed

### ISSUE THREAD

**Issue by raulgenially** [minodisk/bigquery-runner#11]
Hi!

The new version does not work on my VSCode (My query does not result any information). No error message is displayed.
![image](https://user-images.githubusercontent.com/73470842/168751175-d3d6d899-e8a9-4d64-be85-9c408e5e9f66.png)

**Comment by minodisk** [comment]
@raulgenially 
Thanks so much for reporting back!
I've reproduced it, fixed it and released v0.0.52.
Please try updating it.

So far, I am aware that it is not related to the code changed in the extension update, but is caused by a change in the behavior of VS Code's Webview API.
If I postMessage() immediately after creating a Webview, the Promise returned from it was not resolving or rejecting.
Thus, since we know the changed behavior of the Webview API, we fixed it by applying a patch to the extension side.
I think it's a bug in the Webview API, but I couldn't find an Issue that looks like it, so I'm not sure.

**Comment by raulgenially** [comment]
@minodisk 

thanks for taking a look!!
