### ISSUE TITLE
How to download the results table?

### ISSUE THREAD

**Issue by umernalla** [minodisk/bigquery-runner#16]
Hi,
Thanks for writing this great extension.
Can you advise how I can download/save the results to a file?
I thought I saw something in the Extension settings earlier - where I could change the output to a file.
But the extension was changed and I had to reload it - and now I cannot see the same setting?
I tried restarting VS Code - but I still cannot see it.
Thanks.

**Comment by minodisk** [comment]
@umernalla 
Thanks for asking the question 😉 

I added a download button to the viewer in v1.0.0.
If you want to save a table to a file, you can do so from the viewer's download button.
I have also added some options to the download process.
- `bigqueryRunner.downloader.csv.delimiter`.
- `bigqueryRunner.downloader.csv.header`.
- `bigqueryRunner.downloader.rowsPerPage`.
The details are in [the documentation](https://github.com/minodisk/bigquery-runner/blob/6f2a2bd7285febe11044bc32b3c6770663eb0a29/README.md#bigqueryrunnerdownloadercsvdelimiter).

I also removed the output destination option because it would make the code too complicated.
[CHANGELOG.md | v1.0.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#removed)

I believe the flow of viewing the table results in the viewer and then downloading satisfies most of the use cases.
However, if you must output directly to a file, please let me know the specific use case 👍

**Comment by umernalla** [comment]
Hi @minodisk 
Thanks for the prompt reply. Sorry for the silly question, I did notice the download button.
However, when I try to download, there is no file created.
I tried several different format - CSV, MD and plain text and also tried saving in various folders.
I also tried to create the blank file first and then select the file for output - same - nothing is written to disk.
The VS Code output window certainly shows progress e.g.
_[downloader] [markdown] start downloading to /C:/Temp/test.md
[downloader] [markdown] job created <xxx>
[downloader] [markdown] table fetched <xxx>
[downloader] [markdown] flat created SecondsAgg, UpdateCount
[downloader] [markdown] writing head
[downloader] [markdown] writing body
[downloader] [markdown] fetched 10000 rows
[downloader] [markdown] page 1 - 10000
[downloader] [markdown] written 10000 rows
[downloader] [markdown] fetched 10000 rows
[downloader] [markdown] page 10001 - 20000
[downloader] [markdown] written 10000 rows
[downloader] [markdown] fetched 10000 rows
[downloader] [markdown] page 20001 - 30000
[downloader] [markdown] written 10000 rows
[downloader] [markdown] fetched 7954 rows
[downloader] [markdown] page 30001 - 37954
[downloader] [markdown] written 7954 rows
[downloader] [markdown] writing foot
[downloader] [markdown] complete_
But there is no file present once complete.
I also got a colleague to try the same on his PC and he also confirms that no file is written?

**Comment by minodisk** [comment]
@umernalla 
I didn't check it on Windows OS, I'll check it when I'm free 🪟

**Comment by minodisk** [comment]
Reproduced.

![image](https://user-images.githubusercontent.com/514164/177913335-df7a8846-c1e1-4c15-8f4d-69ae9b814584.png)

**Comment by minodisk** [comment]
@umernalla 
I fixed it in v1.1.1, try it.
![image](https://user-images.githubusercontent.com/514164/177965961-5bb101be-55b8-4b11-862e-8efa42d39750.png)

**Comment by umernalla** [comment]
@minodisk Thank you for the prompt fix.
I just tested a CSV file and MD file and they worked!

**Comment by minodisk** [comment]
Now we can download with command in [v1.6.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v160)
#20

**Comment by minodisk** [comment]
We can now see the download progress in [v1.10.0](https://github.com/minodisk/bigquery-runner/blob/main/CHANGELOG.md#v1100).
#19
