### ISSUE TITLE
Ignore query parameter triggers ('?' and '@') in certain strings

### ISSUE THREAD

**Issue by Rock-it-science** [minodisk/bigquery-runner#29]
I am a new user of this extension and have been loving it so far, but have noticed that the query parameter feature causes issues for strings (regex strings for example) where '@' and '?' should remain as those characters, and not trigger query parameters.
Thanks!

**Comment by Rock-it-science** [comment]
If anyone else has this issue, a temporary solution is to use v1.0.0 which was before the query parameter feature was added.

**Comment by minodisk** [comment]
@Rock-it-science 

Thanks for reporting back!
I've fixed the parser for the two cases listed below and released it as v1.12.3, so please give it a try.
If it's not fixed in your case or if you find other cases of mistakes, please let me know 😄 

- https://github.com/minodisk/bigquery-runner/blob/af3e48734bdc8d67fdf9d3ab934ce3ad6e155f3e/packages/misc/queries/params-named-with-strings.bqsql
- https://github.com/minodisk/bigquery-runner/blob/af3e48734bdc8d67fdf9d3ab934ce3ad6e155f3e/packages/misc/queries/params-positional-with-strings.bqsql

**Comment by Rock-it-science** [comment]
Looks like this fixed my issue, thank you!
